### ISSUE TITLE
Missing apt-transport-https

### ISSUE THREAD

**Issue by RonaldEnsing** [ros-infrastructure/buildfarm_deployment_config#36]
I am running Ubuntu Server 16.04 and encountered an issue with deploying the buildfarm using `install_prerequisites.bash` and `reconfigure.bash`.

It only deploys successfully when installing `apt-transport-https` first, before deploying with `install_prerequisites.bash` and `reconfigure.bash`. Otherwise it fails on installing Docker.

**Comment by gavanderhoorn** [comment]
> Otherwise it fails on installing Docker.

Because `apt` is unable to interact with the Docker apt repository as it is configured to use the `https` transport (which is missing).

Error message seen:

```
Package 'docker-ce' has no installation candidate
```

**Comment by nuclearsandwich** [comment]
I've just opened https://github.com/ros-infrastructure/buildfarm_deployment_config/pull/40 which aims to resolve this by adding apt-transport-https to the packages installed by the prerequisites script.

For now I think this is more reasonable than adding the dependency in puppet since this is a side effect  of our default configuration.
