### ISSUE TITLE
Adding import_indigo to reprepro config?

### ISSUE THREAD

**Issue by dejanpan** [ros-infrastructure/buildfarm_deployment_config#5]
Would it be a good idea to add configuration file for importing upstream ros-indigo (or others) packages to https://github.com/ros-infrastructure/buildfarm_deployment_config/blob/master/repo/common.yaml#L132?

This way one would not need to manually perform this step: https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/custom_rosdistro.rst#import-ros-packages-which-are-not-built-by-the-custom-build-farm.

Example yaml file for all ros-indigo packages

```
name: backfill-ros
method: http://packages.ros.org/ros/ubuntu/
suites: [trusty]
component: main
architectures: [amd64, source]
filter_formula: Package (% ros-indigo-* )
```

**Comment by mathias-luedtke** [comment]
It should not be run by default, because it would break full forks.
However, the documentation should point out that it can be listed in the reprepro_config.
Maybe it should be added, but commented out?

It took me hours to figure out that I need this task even without a custom rosdistro, but with package whitelisting.

**Comment by tfoote** [comment]
With https://github.com/ros-infrastructure/ros_buildfarm/pull/130 in place you will be able to add any config you want into your buildfarm_deployment_config `jenkins-slave::reprepro_config:` list of files and not have to worry about commenting it out anymore.
